---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: {{.Values.name}}
  labels:
    app: {{template "name" .}}
    k8s-app: fluent-bit-logging
    version: v1
    kubernetes.io/cluster-service: "true"
    chart: "{{template "namewithversion" .}}"
    release: "{{.Release.Name}}"
    heritage: "{{.Release.Service}}"
spec:
  template:
    metadata:
      labels:
        k8s-app: fluent-bit-logging
        version: v1
        kubernetes.io/cluster-service: "true"
    spec:
      serviceAccountName: {{.Values.name}}
      containers:
        - name: {{.Values.name}}
          image: {{.Values.image}}
          imagePullPolicy: Always
          env:
          - name: FLUENT_ELASTICSEARCH_HOST
            value: "{{.Values.elasticSearchHost}}"
          - name: FLUENT_ELASTICSEARCH_PORT
            value: "{{.Values.elasticSearchPort}}"
          - name: FLUENT_ELASTICSEARCH_USER # even if not used they are necessary
            value: "{{.Values.elasticSearchUsername}}"
          - name: FLUENT_ELASTICSEARCH_PASSWORD # even if not used they are necessary
            value: "{{.Values.elasticSearchPassword}}"
          - name: FLUENT_TIMESTAMP
            value: “{{.Values.fluentTimeStamp}}”
          resources:
            requests:
              cpu: {{.Values.resources.requests.cpu}}
              memory: {{.Values.resources.requests.mem}}
            limits:
              cpu: {{.Values.resources.limits.cpu}}
              memory: {{.Values.resources.limits.mem}}
          ports:
          - containerPort: 2020
          volumeMounts:
          - name: fbconfig
            mountPath: /fluent-bit/etc/fluent-bit.conf
            subPath: fluent-bit.conf
          - name: fbconfig
            mountPath: /fluent-bit/etc/parsers.conf
            subPath: parsers.conf
          - name: varlog
            mountPath: /var/log
            readOnly: true
          - name: runlog
            mountPath: /run/log
            readOnly: true
          - name: varlibdockercontainers
            mountPath: /var/lib/docker/containers
            readOnly: true
      {{- if .Values.tolerations}}
      tolerations:
      {{- range .Values.tolerations}}
      - key: {{.key | default ("")}}
        value: {{.value | default ("")}}
        operator: {{.operator | default ("Equal")}}
        effect: {{.effect | default ("")}}
      {{- end}}
      {{- end}}
      terminationGracePeriodSeconds: 10
      volumes:
      - name: fbconfig
        configMap:
          name: {{ template "name" . }}
      - name: varlog
        hostPath:
          path: /var/log
      # Some operating systems store logs in /run/log
      # https://goo.gl/apMdJY https://goo.gl/WaHSNf
      - name: runlog
        hostPath:
          path: /run/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
