# Default values.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

name: fluent-bit
image: quay.io/samsung_cnct/fluent-bit-container:v0.0.2

resources:
  requests:
    cpu: 100m
    mem: 500Mi
  limits:
    cpu: 300m
    mem: 1000Mi

elasticSearchHost: elasticsearch
elasticSearchPort: 9200

#  example toleration
#tolerations:
#  - key: taintKey
#    value: taintValue
#    operator: Equal
#    effect: NoSchedule
