---
name: fluent-bit
image: fluent/fluent-bit:0.14.1

cluster_uuid: 00000000-0000-0000-0000-000000000000

resources:
  requests:
    cpu: 100m
    mem: 500Mi
  limits:
    cpu: 300m
    mem: 1000Mi

elasticSearchHost: elasticsearch
elasticSearchPort: 9200
elasticSearchUsername: elastic
elasticSearchPassword: changeme
fluentTimeStamp: flutime

test:
  image: quay.io/samsung_cnct/e2etester:prod

#config: |-

#parsers: |-
